import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { InquiryForm } from "@/components/forms/InquiryForm";
import { getCategory, getProduct, products } from "@/lib/products";
import { siteConfig, whatsappHref } from "@/lib/site";
export function generateStaticParams() { return products.map((product) => ({ category: product.category, slug: product.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ category: string; slug: string }> }): Promise<Metadata> { const { category, slug } = await params; const product = getProduct(category, slug); return product ? { title: product.name, description: product.shortDescription, openGraph: { title: `${product.name} | ${siteConfig.brandName}`, description: product.shortDescription } } : {}; }
export default async function ProductPage({ params }: { params: Promise<{ category: string; slug: string }> }) { const { category: categorySlug, slug } = await params; const product = getProduct(categorySlug, slug); const category = getCategory(categorySlug); if (!product || !category) notFound(); const related = products.filter((item) => item.category === product.category && item.slug !== product.slug).slice(0, 3); const schema = { "@context": "https://schema.org", "@type": "Product", name: product.name, description: product.shortDescription, brand: { "@type": "Brand", name: siteConfig.brandName } }; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Products", href: "/products" }, { label: category.name, href: `/products/${category.slug}` }, { label: product.name }]} /><section className="section"><div className="content-wrap quote-layout"><article><div className="placeholder-image">TODO: Replace with authorized product image.</div><p className="eyebrow">{product.status}</p><h1>{product.name}</h1><p>{product.shortDescription}</p><h2>Core specifications</h2><ul className="spec-list">{product.keySpecifications.map((spec) => <li key={spec.label}><strong>{spec.label}:</strong> {spec.value}</li>)}</ul><h2>Applications</h2><ul>{product.applications.map((application) => <li key={application}>{application}</li>)}</ul><h2>Technical specifications</h2><ul className="spec-list">{product.technicalSpecifications.map((spec) => <li key={spec.label}><strong>{spec.label}:</strong> {spec.value}</li>)}</ul><h2>Documentation</h2><div className="card"><p>TODO: Replace with verified certificate or test document.</p><p>TODO: Replace with verified product specifications.</p></div></article><aside className="quote-card"><h2>Request a Quote</h2><p>Share your application and required quantity for a tailored recommendation.</p><div className="cta-row"><Link className="button button-primary" href={`/request-a-quote?product=${product.slug}`}>Request a Quote</Link><a className="button button-outline" href={whatsappHref}>WhatsApp Us</a></div></aside></div></section><section className="section section-alt"><div className="content-wrap"><h2>Related Products</h2><div className="grid">{related.map((item) => <article className="card" key={item.id}><h3>{item.name}</h3><p>{item.shortDescription}</p><Link className="button button-outline" href={`/products/${item.category}/${item.slug}`}>View Details</Link></article>)}</div></div></section><section className="section"><div className="content-wrap"><h2>Discuss this equipment placeholder</h2><InquiryForm productModel={product.name} /></div></section></>; }
