import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { PageHero } from "@/components/PageHero";
import { getCategory, products } from "@/lib/products";
export function generateStaticParams() { return ["air-compressors", "drilling-rigs", "solar-light-towers", "magnetic-separators"].map((category) => ({ category })); }
export async function generateMetadata({ params }: { params: Promise<{ category: string }> }): Promise<Metadata> { const { category } = await params; const data = getCategory(category); return data ? { title: data.name, description: data.summary } : {}; }
export default async function CategoryPage({ params }: { params: Promise<{ category: string }> }) { const { category: slug } = await params; const category = getCategory(slug); if (!category) notFound(); const entries = products.filter((product) => product.category === category.slug); return <><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Products", href: "/products" }, { label: category.name }]} /><PageHero eyebrow="Product Category" title={category.name} description={category.summary} /><section className="section"><div className="content-wrap"><h2>Replaceable product placeholders</h2><p>Use the equipment cards below as a structural placeholder until verified product information is supplied.</p><div className="grid">{entries.map((product) => <article className="card" key={product.id}><div className="placeholder-image">TODO: Replace with authorized product image.</div><h3>{product.name}</h3><p>{product.shortDescription}</p><ul className="spec-list">{product.keySpecifications.map((spec) => <li key={spec.label}>{spec.label}: {spec.value}</li>)}</ul><div className="cta-row"><Link className="button button-outline" href={`/products/${product.category}/${product.slug}`}>View Details</Link><Link className="button button-primary" href={`/request-a-quote?product=${product.slug}`}>Request a Quote</Link></div></article>)}</div></div></section><section className="section section-alt"><div className="content-wrap"><h2>How to Choose</h2><p>Confirm your material, operating environment, power availability, output requirement and safety constraints with an engineer before selecting a model.</p><Link className="button button-primary" href="/contact">Contact an Engineer</Link></div></section></>; }
