import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { PageHero } from "@/components/PageHero";
import { getCategory, productCategories, products } from "@/lib/products";
import { pageMetadata } from "@/lib/seo";
export function generateStaticParams() { return productCategories.map((category) => ({ category: category.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ category: string }> }): Promise<Metadata> { const { category } = await params; const data = getCategory(category); return data ? pageMetadata(data.name, data.summary, `/products/${data.slug}`) : {}; }
export default async function CategoryPage({ params }: { params: Promise<{ category: string }> }) { const { category: slug } = await params; const category = getCategory(slug); if (!category) notFound(); const entries = products.filter((product) => product.category === category.slug); return <><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Products", href: "/products" }, { label: category.name }]} /><PageHero eyebrow="Product Category" title={category.name} description={category.summary} /><section className="section"><div className="content-wrap"><h2>{category.name} Catalog</h2><p>Review the published model references and available technical data. Confirm site conditions and final configuration with our team before ordering.</p><div className="grid">{entries.map((product) => <article className="card" key={product.id}>{product.heroImage ? <Image className="card-image" src={product.heroImage} alt={`${product.name} product view`} width={720} height={540} sizes="(max-width: 800px) 92vw, 25vw" /> : <div className="placeholder-image">Product image available with your quotation request.</div>}<h3>{product.name}</h3><p>{product.shortDescription}</p><ul className="spec-list">{product.keySpecifications.map((spec) => <li key={spec.label}>{spec.label}: {spec.value}</li>)}</ul><div className="cta-row"><Link className="button button-outline" href={`/products/${product.category}/${product.slug}`}>View Details</Link><Link className="button button-primary" href={`/request-a-quote?product=${product.slug}`}>Request a Quote</Link></div></article>)}</div></div></section><section className="section section-alt"><div className="content-wrap"><h2>How to Choose</h2><p>Confirm your material, operating environment, power availability, output requirement and safety constraints with an engineer before selecting a model.</p><Link className="button button-primary" href="/contact">Contact an Engineer</Link></div></section></>; }
